name: date_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  outline_gradient_button: ^1.0.0+2
  gradient_input_border: ^1.0.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  provider: ^4.3.2+2

  font_awesome_flutter: ^8.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/images/users/
  fonts:
    - family: Roboto-Black
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 700

  uses-material-design: true